# Generated by Django 3.2.16 on 2023-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_transcations',
            name='bank_account',
        ),
    ]
