# Generated by Django 3.2.16 on 2023-03-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_bank_transcations_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_ledger'),
        ),
    ]
