# Generated by Django 3.2.16 on 2023-03-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_bank_transcations_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('j_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.journal_voucher')),
            ],
        ),
    ]
