# Generated by Django 3.2.16 on 2023-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_journal_particulars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank_transcations',
            new_name='bank_transactions',
        ),
        migrations.AddField(
            model_name='godown_items',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
