# Generated by Django 3.2.16 on 2023-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_ledger_vouchers_new_subgroup_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='per',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='rate',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='units',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='value',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
