# Generated by Django 3.2.16 on 2023-07-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230724_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_no', models.IntegerField(blank=True, null=True)),
                ('dispatch_doc_no', models.IntegerField(blank=True, null=True)),
                ('dispatched_throught', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('carrier_name_agent', models.CharField(max_length=200, null=True)),
                ('bill_of_lading', models.CharField(max_length=200, null=True)),
                ('mototr_vehicle_no', models.CharField(max_length=200, null=True)),
                ('date1', models.CharField(max_length=200, null=True)),
                ('date2', models.CharField(max_length=200, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='party_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_bill_to', models.CharField(max_length=200)),
                ('mailing_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=280)),
                ('states', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_reg_type', models.CharField(max_length=200)),
                ('gstn_un', models.CharField(max_length=200)),
                ('place_of_supply', models.CharField(default='Kerala', max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('dispatch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail')),
            ],
        ),
        migrations.CreateModel(
            name='sales_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('party_ac_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_ledger', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_item', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('dispatch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail')),
                ('party_detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.party_details')),
            ],
        ),
        migrations.CreateModel(
            name='sales_voucher_stock_item_one_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('party_ac_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_ledger', models.CharField(blank=True, max_length=200, null=True)),
                ('per', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('dispatch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail')),
                ('party_detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.party_details')),
                ('sale_invo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_invoice')),
            ],
        ),
        migrations.CreateModel(
            name='sales_voucher_stock_item_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('per', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('dispatch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.dispatch_detail')),
                ('party_detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.party_details')),
                ('sales_voucher_stock_item_one_allocation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sales_voucher_stock_item_one_allocation')),
            ],
        ),
    ]
