# Generated by Django 4.2.1 on 2023-09-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dispatch_detail_party_details_sales_invoice_sales_voucher_stock_item_allocation_sales_voucher_stock_'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_id', models.IntegerField(null=True)),
                ('sup_inv_no', models.CharField(max_length=255, null=True)),
                ('sup_inv_date', models.DateField(blank=True, null=True)),
                ('vouch_date', models.DateField(blank=True, null=True)),
                ('party_accname', models.CharField(max_length=255, null=True)),
                ('purchase_ledger', models.CharField(max_length=255, null=True)),
                ('receipt_doc_no', models.CharField(max_length=255, null=True)),
                ('dispatched_through', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('carriername_agent', models.CharField(max_length=255, null=True)),
                ('bill_of_lading', models.CharField(max_length=255, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('motor_vehicle_no', models.CharField(max_length=255, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('gst_treatment', models.CharField(max_length=255, null=True)),
                ('gst_number', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='receipt_note_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_voucher')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('per', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('purchase_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_voucher')),
            ],
        ),
    ]
